<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/9/20 0020
 * Time: 22:29
 */

namespace app\service\controller;


use app\BaseController;
use think\exception\HttpResponseException;
class Base extends BaseController
{
    public $serviceUser;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function isLogin()
    {
        $this->serviceUser = session(config('service.session_service'));
        if(empty($this->serviceUser)){
            return false;
        }else{
            return true;
        }
    }

    /**
     * @param mixed ...$args
     */
    public function redirect(...$args)
    {
        throw new HttpResponseException(redirect(...$args));
    }
}